version: '3.10'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - ./data:/data
