version: "3.10"

services:

  python-db-1:
    image: python-app
    environment:
      - POSTGRES_PASSWORD=6969


  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - "./postgres:/var/lib/postgresql/data"


  app:
    build: .
    volumes:
      - .:/Python
    ports:
    - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
