version: "3.10"

services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
    - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - db_data:/data

volumes:
  db_data:
